services:
  fryfrog-hub-api:
    image: ghcr.io/xbwsh/fryfrog-hub-api:latest
    # 本地构建改用下面这行，注释掉上面的 image
    # build: .
    container_name: fryfrog-hub-api
    restart: unless-stopped
    ports:
      - "20058:20058"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./db:/data
